import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { ToastProvider } from "@/context/ToastContext";
import { ConsoleProvider } from "@/context/ConsoleProvider";

export const metadata: Metadata = {
  title: "N1 Interview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-background text-text">
        <ErrorBoundary>
          <ConsoleProvider>
            <AppProvider>
              <ToastProvider>
                {children}
              </ToastProvider>
            </AppProvider>
          </ConsoleProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
